graphql:
    spqr:
        gui:
            enabled: true
spring:
    h2:
        console:
            enabled: true
            path: /book-api

datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: